apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-experiment-deployment1
  labels:
    app: cloud-experiment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-experiment
  template:
    metadata:
      labels:
        app: cloud-experiment
    spec:
      containers:
      - name: cloud-experiment
        image: docker.wigwag.io/cloud-experiment:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
